### ISSUE TITLE
Use Semantic Versioning 2.0.0

### ISSUE THREAD

**Issue by TitusKirch** [nitrado/NitrAPI-PHP#76]
Hello,
I would hereby suggest to use "[Semantic Versioning 2.0.0](https://semver.org)" for versioning this library. Some versions had 2 places, some 3. In addition, it is currently inconclusive what a change of the first digit, the second digit and sometimes the third digit means.

**Comment by NitradoTimo** [comment]
We will keep that in mind when we create new tags :+1:

**Comment by TitusKirch** [comment]
Thank you very much for the answer. To be honest, I had forgotten about the issue by now and maintain my own fork of this library from time to time with more up-to-date dependencies including fixes/updates from the code.

Thanks anyway.
